language: node_js
sudo: false
node_js:
  - "4.1"
install:
  - npm install
script:
  - npm test
after_success:
  - npm run deploy
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
